trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet build --configuration Release
  displayName: 'Build project'

- script: dotnet test --configuration Release --no-build
  displayName: 'Test project'
